---
all:
        children:
                devops:
                        hosts:
                                demo:
                                        ansible_hosts: 10.128.0.2
              
